services:

  db:
    image: postgres:15
    container_name: postgresdb
    ports:
    # Local/Docker
      - "5432:5432"
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: geheim123
      POSTGRES_DB: restdemodb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sqlinit:/docker-entrypoint-initdb.d/

  tomcat:
    build:
      context: ./
      dockerfile: tomcat.dockerfile
    image: esempe_tomcat:latest
    container_name: tomcat
    restart: always
    ports:
    # Local/Docker
      - "8080:8080"
    depends_on:
     - db
    volumes:
      - ./webapps:/usr/local/tomcat/webapps/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@info.de
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - pgadmindata:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmindata: