services:

  postgresdb:
    image: postgres:15
    container_name: postgresdb
    ports:
    # Local/Docker
      - "5432:5432"
    environment:
      POSTGRES_USER: userdb
      POSTGRES_PASSWORD: geheim123
      POSTGRES_DB: restdemodb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sqlinit:/docker-entrypoint-initdb.d/

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  tomcat:
    build:
      context: ./
      dockerfile: tomcat.dockerfile
    image: esempe_tomcat:latest
    container_name: tomcat
    restart: always
    environment:
      - CATALINA_OPTS=-agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
    ports:
    # Local/Docker
      - "8080:8080"
      - "5005:5005" 
    volumes:
      - ./webapps:/usr/local/tomcat/webapps/

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@info.de
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgresdb
    volumes:
      - pgadmindata:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmindata:
  mongodata: